package de.unistuttgart.iste.meitrex.gamification_service.events.repository;

import de.unistuttgart.iste.meitrex.gamification_service.events.persistent.PersistentForumActivityEvent;
import de.unistuttgart.iste.meitrex.gamification_service.events.persistent.PersistentUserSkillLevelChangedEvent;


public interface IPersistentUserSkillLevelChangedEventRepository extends IPersistentEventRepository<PersistentUserSkillLevelChangedEvent> {

}
