package de.unistuttgart.iste.meitrex.gamification_service.events.repository;

import de.unistuttgart.iste.meitrex.gamification_service.events.persistent.PersistentAskedTutorAQuestionEvent;

public interface IPersistentAskedTutorAQuestionEventRepository extends IPersistentEventRepository<PersistentAskedTutorAQuestionEvent> {
}
